### PR TITLE
Switch to eslint

### PR DESCRIPTION
**Pull request by compwright**
jshint is no longer actively maintained, and has security vulnerabilities.

Since eslint requires Node.js 6+, this PR drops support for Node.js 4-5.

### CODE REVIEW

**Comment by thomseddon** [comment]
Thanks, this has been fixed in #511

**Comment by compwright** [comment]
@thomseddon I'm glad you're working on this, but I'm puzzled why you declined mine, especially since mine fixes all the security issues that `npm audit` warns about, and #511 does not (yet). I've left feedback on that PR where it could be improved.

**Comment by thomseddon** [comment]
Hmm, maybe I was too rash with this! I hand't noticed that jslint was dead and assumed all the line changes were superfluous - now I see they were actually lint fixes! Which makes this even more awesome.


Will close #511 in preference for this

**Comment by thomseddon** [comment]
Only issue I can see is that eslint doesn't seem work with node 4.

Is there any way we can keep support?

**Comment by compwright** [comment]
@thomseddon IMO, it's time to move on. Node 4 is EOL. Perhaps this should be released as 3.1 instead of 3.0.1. I'll update `engines`.

**Comment by mjsalinger** [comment]
@thomseddon I think we should drop support for node 4.  Node 4 is EOL and no longer supported by node core.  In general we should support the versions that are considered active by node.js - so currently, it's 6, 8, and 10..

**Comment by thomseddon** [comment]
:+1: to drop support for 4, all looks good LGTM

**Comment by mjsalinger** [comment]
A point was made in #496 that we should merge non-breaking changes into 3.1.0 (especially since we're dropping support for 4.x) before making a non-breaking release.  Can we refactor this PR to support 4.x for now?  We'll drop support for 4.x very soon.

**Comment by mjsalinger** [comment]
@compwright Can you rebase your changes against the `dev` branch and fix conflicts?  I'd like to merge the eslint change into 4.x..

**Comment by compwright** [comment]
@mjsalinger good to go! Thanks

**Pull request merged**
