### PR TITLE
Fix `hasOwnProperty is not a function` error

### PR DESCRIPTION
**Pull request by Pritilender**
Writing koa adapter, I came accros an error when I pass `ctx.response` to make a new `Response` object which stated that `options.headers.hasOwnProperty is not a function`.
I've found that I'm not alone and that there was an issue: #413 (which, btw, is closed, but don't know why).

The origin of this error could be that somewhere in koa, or wherever, `headers` are created using `Object.create(null)`.
This PR changes the way of calling `hasOwnProperty` so even if an object is created with `Object.create(null)`, we can still check for own properties.

Also, there are two more places where `hasOwnProperty` is called as a prototype function of the object, not as direct call to prototype function, but I haven't changed them.
Should I changed them also or no?

### CODE REVIEW

**Comment by Pritilender** [comment]
Oh and also because I have the latest npm (v5 something), it created `package-lock.json` automatically, so I think it's better to include it in the project also.

**Comment by maxtruxa** [comment]
@Pritilender Could you change the target branch to `oauthjs:dev`?

**Comment by Pritilender** [comment]
@maxtruxa Yes, I'll do it some time tonight. Sorry, haven't seen the comment.

**Comment by Pritilender** [comment]
@maxtruxa sorry I was quite busy that day when I've told that I'll update the branch... I updated the branch and reverted `package-lock.json`. I'll submit new PR now for `package-lock.json`.

**Comment by KingWu** [comment]
Will publish this fix?

**Comment by djoq** [comment]
+1 on timeline for publishing.

**Comment by zo-chu** [comment]
+1

**Comment by marceloch2** [comment]
Any news on this issue?

To keep coding i have commented this lines.

// Store the headers in lower case.
  for (var field in options.headers) {
    if (options.headers.hasOwnProperty(field)) {
      this.headers[field.toLowerCase()] = options.headers[field];
    }
  }

**Comment by Vergil0327** [comment]
Is this issue fixed ?
I still got this error in koa v.2.5.1

type error: options.headers.hasOwnProperty is not a function
at /oauth2-server/lib/response.js:16:25

**Comment by Vergil0327** [comment]
When will this patch be published ?

**Comment by Vergil0327** [comment]
The error will gone when change four lines of code like below.
But why does this fixed patch still not published ?

https://github.com/oauthjs/node-oauth2-server/pull/430/commits/92f0a0be32dfd368f534270cd4d0e03c45f51cfe
https://github.com/oauthjs/node-oauth2-server/pull/430/commits/68ef835f336bb1635e62afba6218f0d57abeada0

**Comment by Pritilender** [comment]
@Vergil0327 you can reference the dev branch in your package.json until someone from the maintainers publish it to npm.

**Comment by Pritilender** [comment]
@t1bb4r As I still actively use this module in my projects, I can say that it's not pushed under current release on npm. I have v3.0.1 as my dependency for a current project (Express based, so no problems like this) and it doesn't include the code I changed in this PR.
I am not sure what's going on with v4. But I think that this is not a braking change and that it could be published as some patch version for v3 (paging @maxtruxa @mjsalinger).

**Comment by KingWu** [comment]
@djoq Still wait for publishing

**Comment by leonaves** [comment]
+1 pls publish

**Comment by djoq** [comment]
@KingWu see https://github.com/oauthjs/node-oauth2-server/pull/430#issuecomment-390223303

**Pull request merged**
