### PR TITLE
Fix non-expiring tokens

### PR DESCRIPTION
**Pull request by rluba**
[According to the changelog](https://github.com/oauthjs/node-oauth2-server/blob/4090055df44d5e199c816e298c685b78e86c5b85/CHANGELOG.md#150) `oauth2-server ` should support non-expiring tokens by setting ` accessTokenLifetime`/`refreshTokenLifetime` to `null`.

 This doesn’t work in the current version due to bugs in `token-handler` and `abstract-grant-type`. This PR fixes those issues.

### CODE REVIEW

**Comment by mjsalinger** [comment]
@rluba I've reset the PR to use `dev` as a base, and there are some conflicts.  Can you rebase/fix the conflicts?

**Comment by rluba** [comment]
@mjsalinger Sorry for the delay. I’ve updated the branch to fix the conflicts.

**Comment by rluba** [comment]
@mjsalinger Is there anything stopping this PR from being merged?

**Comment by rluba** [comment]
@mjsalinger Sorry to bother you again, but this PR has been open for a year. Is there anything preventing it from being merged?

**Pull request closed without merging**
