### PR TITLE
Implicit grant flow v3

### PR DESCRIPTION
**Pull request by abelaska**
Good news everyone, I've integrated implicit grant flow. Feedback is more than welcome!

### CODE REVIEW

**Comment by rcosgrave** [comment]
+1

**Comment by dylanwilder** [comment]
any updates here? this would be great to have

**Comment by rcosgrave** [comment]
Hey Dylan, so instead of waiting. I took the 'current' version of 3.x.x and just copied the changed files from this PR and put them in my copy. There was a couple of debugging things i did like changing _.contains () to _.includes ()

Please note you will probably need to catch the response_type in your authorize call to put the access tolen in the querystring and send back if it's 'token' rather than the code

**Comment by CestDiego** [comment]
+1

**Comment by codeitcody** [comment]
Thank you for doing this! Would love to see this merged. Implicit makes life much easier with certain types of applications.

**Comment by mjsalinger** [comment]
@abelaska If you want to rebase, I'll merge it in.

**Comment by mjsalinger** [comment]
This PR needs to be rebased against the latest master.  If anyone wants to take that on, I'll merge it in.

**Comment by dannydeut** [comment]
Implemented the module last week, really like it. What are the plans on the Implicit Grant? When is it expected?

**Comment by dannydeut** [comment]
Anyone?

**Comment by dannydeut** [comment]
Any updates? I would be happy to help/contribute, if this speeds things up.

**Comment by maxtruxa** [comment]
@dannydeut As mjsalinger already said, the PR needs to be rebased against the current ~~master~~ dev branch before it can be merged.

**Comment by dannydeut** [comment]
As mentioned above, I took the master branch and added the changes to a copy. With some minor changes I got it to work. Not ideal, because would like to use future update. But it works for now. I'm not a git expert, so I can not help you with rebasing. I hope it will be rebased/merged soon. Keep up the good work.

**Comment by adieuadieu** [comment]
I've rebased this with the `dev` branch in #464.

**Comment by mjsalinger** [comment]
Closing in favor of #464.

**Pull request closed without merging**
