### PR TITLE
Updated dependencies

### LINKED ISSUE #380: Update dependencies before 3.0.0 release
Update dependencies in `package.json` before 3.0.0 is released.

### PR DESCRIPTION
**Pull request by mjsalinger**
Fixes #380

Updated dependencies to latest versions.
Changed lodash `contains` to `includes`
Changed one should comparison

### CODE REVIEW

**Comment by andrewmaillet** [comment]
LGTM

**Comment by maxtruxa** [comment]
@mjsalinger Hey, thanks! Did you intentionally remove the caret (`^`) from all version numbers?

**Comment by mjsalinger** [comment]
I tend to be more in favor of pinned dependencies, because ^ and ~ dependencies can lead to bugs creeping in, and sometimes breaking changes that aren't meant to be breaking.  The pinned, static dependency version leads to the idea that this library for this version passed all its tests with the specified dependencies, and that a change in a downstream dependency shouldn't break anything.  Basically we should be keeping on top of dependency changes and test them and upgrade them regularly in the library.  

This is my preference but I'm open to other arguments...

**Comment by maxtruxa** [comment]
@mjsalinger That's true. On the other hand all mature packages should be using semver, which means neither `^` nor `~` should break anything.. `~` would allow bugfixes in dependencies without touching our `package.json`.
A less strict definition of dependency versions also possibly reduces overhead for applications using this module and one of the dependencies itself. Depending on `lodash@4.17.5` would result in two copies of lodash being installed, while `~lodash@4.17.4` in our `package.json` would allow npm to install lodash just once.

Anyway, I just wanted to make sure this didn't happen by accident. Both approaches have their own pros and cons. Keep it like it is 👍

**Pull request merged**
