### PR TITLE
Pass correct "this" to the model.

### PR DESCRIPTION
**Pull request by danbell**
This PR allows "this" to be used within the model. This completes and obsoletes #320.

### CODE REVIEW

**Comment by cirick** [comment]
I tested this change and it works for me as well. This change allows me to pass in class objects for the model and retain proper "this" context.

**Comment by cirick** [comment]
@mjsalinger What do you think about this change?

**Comment by elmolicious** [comment]
This is feature I would love to see.

For anyone who wants to use a class for the model right now:

Currently a simple (but annoying) fix is to bind the model functions to the model context in the class constructor:

this.generateAuthorizationCode = this.generateAuthorizationCode.bind(this);

**Comment by mjsalinger** [comment]
@danbell Can you rebase?  I'll merge it if you do.

**Comment by danbell** [comment]
@mjsalinger - done!

**Pull request merged**
