### PR TITLE
docs: Correct tokens time scale for 2.x to 3.x  migration guide

### PR DESCRIPTION
**Pull request by iczechowski**

### CODE REVIEW

**Comment by mjsalinger** [comment]
@iczechowski Please change this PR to point to the `dev` branch.

**Comment by iczechowski** [comment]
@mjsalinger done.

**Comment by blazedd** [comment]
Any status on this? I had to spend some time making sure my access token wouldn't expire in 3.6 seconds because of this.

**Comment by markstos** [comment]
I've compared the docs against the code and confirmed this doc-patch is correct. A merge is recommended.

**Review by mjsalinger — APPROVED** [review]
LGTM

**Pull request merged**
