### PR TITLE
renamed token type from bearer to Bearer

### PR DESCRIPTION
**Pull request by omerlh**
On authorization header, the token type expected to Bearer and not bearer. I changed the token the server return after authentication for consistence.

### CODE REVIEW

**Comment by thomseddon** [comment]
Wow, this is absolutely correct: https://tools.ietf.org/html/rfc6750#section-4

Breaking change so will have to hit a later release

**Comment by omerlh** [comment]
OK, glad I can help.

**Comment by ruimarinho** [comment]
Indeed, very well spotted @omerlh. It looks like this bug [transitioned to the 3.0.0 rewrite too](http://github.com/oauthjs/node-oauth2-server/blob/cd7776ce19b4e55a0e5800d78e4186c741711b36/lib/token-types/bearer-token-type.js#L31). We will get this merged.

**Comment by mjsalinger** [comment]
Superceded by #340

**Pull request closed without merging**
