### PR TITLE
#280 Add alwaysIssueNewRefreshToken server option

### PR DESCRIPTION
**Pull request by visvk**
Add alwaysIssueNewRefreshToken server option

```
{Boolean} alwaysIssueNewRefreshToken
```

Default value is `true`

If false, the refresh token is not revoked and the new one is neither saved nor returned with an access token.

### CODE REVIEW

**Comment by nunofgs** [comment]
Hi @visvk, can you provide a use-case for this feature?

**Comment by visvk** [comment]
Hi, 
My use case: 
I can issue a refresh token with no expiry, so there is no need to issue a new refresh token every time.

as described in the RFC [Refreshing an Access Token section](https://tools.ietf.org/html/rfc6749#section-1.5), 
```
The authorization server MAY issue a new refresh token...
```
but nowadays, the refresh token grant type always issues a new refresh token and revoke the old one.

with option
```
alwaysIssueNewRefreshToken = false
```
the refresh token is not revoked and server does not response with a new one.

**Comment by nunofgs** [comment]
@visvk once PR #274 is merged, you'll be able to simply return from the `revokeToken()` model function without actually revoking your token. I believe this should cover your use-case.

**Comment by visvk** [comment]
@nunofgs sadly, this does not cover the use case.
In The Refresh token grant, The `saveToken()` model function always issues a new refresh token, which is in this scenario unnecessary.
```
The authorization server MAY issue a new refresh token, in which case
  the client MUST discard the old refresh token and replace it with the
  new refresh token.
```
For the use-case, server should not return the new refresh token, because the refresh token is immortal, so there is no reason to discard it. And doing this stuff in model functions is hacky.
Auth Server should assume it in reasonable way.
Google for instance implements refresh token mechanism this way. 

Briefly looking for implementations:
- [PHP OAuth2 server](https://github.com/thephpleague/oauth2-server) implemented `rotateRefreshTokens()` method
- [Spring OAuth](https://github.com/spring-projects/spring-security-oauth) assumes if the refresh token is immortal
- Another [PHP OAuth Server](https://github.com/bshaffer/oauth2-server-php) implemented `always_issue_new_refresh_token` 

But Rails  [doorkeeper](https://github.com/doorkeeper-gem/doorkeeper) refuse to implement this feature

Moreover, I've found another use case: 

Mobile clients often have unreliable internet connectivity. Sometimes they submit the refresh token 
request, the server receives it, generates a new access/refresh token pair and sends it back to the 
client, which... never receives it. So the client will retry the refresh token request, but it will fail 
because the original refresh token has been revoked when the new one was issued. As a result, the
 client is completely logged out and the user has to reauthenticate by entering username / password.

Doorkeeper wouldn't revoke previous refresh token, until the new one is used once. 
But this PR cover the use case too.

**Comment by maxtruxa** [comment]
@oauthjs IMO we should re-open (and actually merge) this PR, since the issue really isn't solved. I'm using these changes for quite some time now in a test setup and there work great 👍

**Comment by mjsalinger** [comment]
Agree with reopening this.  @visvk, can you fix the conflicts?

**Comment by chainlink** [comment]
Working on resolving conflicts for this, should have something shortly

**Comment by chainlink** [comment]
Rebased in https://github.com/oauthjs/node-oauth2-server/pull/347

**Comment by visvk** [comment]
@mjsalinger done

**Pull request merged**
