### PR TITLE
Adding support for config option to expose user_id on access token re…

### PR DESCRIPTION
**Pull request by j0shua**
…sponse

### CODE REVIEW

**Comment by shylesh107** [comment]
+1

**Comment by shylesh107** [comment]
If anyone could merge this PR, that would be great.

**Comment by nunofgs** [comment]
Thank you for your contribution. We'll be adding support for adding custom properties to the response in 3.1.0.

**Comment by mjsalinger** [comment]
This PR has been superceded by the new 3.0 library, and this particular functionality is addressed by #301

**Pull request closed without merging**
